base_url: "https://huggingface.co/chat"
timeout: 60
headers:
  User-Agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36"
  Accept: "application/json"
  Content-Type: "application/json"
parameters:
  temperature: 0.7
  max_new_tokens: 1000
  top_p: 0.9
  repetition_penalty: 1.1

